{{- if .Values.metricsGenerator.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "tempo.metricsGeneratorFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tempo.metricsGeneratorLabels" . | nindent 4 }}
  {{- with .Values.metricsGenerator.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if not .Values.metricsGenerator.autoscaling.enabled }}
  replicas: {{ .Values.metricsGenerator.replicas }}
{{- end }}
  selector:
    matchLabels:
      {{- include "tempo.metricsGeneratorSelectorLabels" . | nindent 6}}
  serviceName: metrics-generator
  podManagementPolicy: Parallel
  updateStrategy:
    rollingUpdate:
      partition: 0
  template:
    metadata:
      labels:
        {{- include "tempo.metricsGeneratorLabels" . | nindent 8 }}
        {{- include "tempo.gossipRing.selectorLabels" . | nindent 8 }}
        {{- with .Values.tempo.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.metricsGenerator.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-tempo.yaml") . | sha256sum }}
        {{- with .Values.tempo.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.metricsGenerator.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "tempo.serviceAccountName" . }}
      containers:
        - args:
            - -target=metrics-generator
            - -config.file=/conf/tempo.yaml
            {{- with .Values.metricsGenerator.extraArgs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          image: {{ include "tempo.metricsGeneratorImage" . }}
          imagePullPolicy: {{ .Values.tempo.image.pullPolicy }}
          name: metrics-generator
          ports:
            - name: grpc
              containerPort: 9095
            - name: http-memberlist
              containerPort: 7946
            - name: http
              containerPort: 3100
          {{- with .Values.metricsGenerator.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.metricsGenerator.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          readinessProbe:
            {{- toYaml .Values.tempo.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.metricsGenerator.resources | nindent 12 }}
          {{- with .Values.tempo.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /conf
              name: tempo-conf
            - mountPath: /var/tempo
              name: data
            {{- with .Values.metricsGenerator.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      terminationGracePeriodSeconds: {{ .Values.metricsGenerator.terminationGracePeriodSeconds }}
      {{- with .Values.metricsGenerator.affinity }}
      affinity:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      {{- with .Values.metricsGenerator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.metricsGenerator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - configMap:
            name: {{ template "tempo.fullname" . }}
          name: tempo-conf
        {{- with .Values.metricsGenerator.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
  {{- if not .Values.metricsGenerator.persistence.enabled }}
        - name: data
          emptyDir: {}
  {{- else }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        {{- with .Values.metricsGenerator.persistence.storageClass }}
        storageClassName: {{ if (eq "-" .) }}""{{ else }}{{ . }}{{ end }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.metricsGenerator.persistence.size | quote }}
  {{- end }}
{{- end }}
