{{- if and .Values.enterprise.enabled .Values.enterpriseFederationFrontend.enabled .Values.enterpriseFederationFrontend.ingress.enabled -}}
{{ $dict := dict "ctx" . "component" "enterprise-federation-frontend"  }}
{{- $ingressApiIsStable := eq (include "tempo.ingress.isStable" .) "true" -}}
{{- $ingressSupportsIngressClassName := eq (include "tempo.ingress.supportsIngressClassName" .) "true" -}}
{{- $ingressSupportsPathType := eq (include "tempo.ingress.supportsPathType" .) "true" -}}
apiVersion: {{ include "tempo.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "tempo.resourceName" $dict }}
  labels:
    {{- include "tempo.labels" $dict | nindent 4 }}
  {{- with .Values.enterpriseFederationFrontend.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and $ingressSupportsIngressClassName .Values.enterpriseFederationFrontend.ingress.ingressClassName }}
  ingressClassName: {{ .Values.enterpriseFederationFrontend.ingress.ingressClassName }}
  {{- end -}}
  {{- if .Values.enterpriseFederationFrontend.ingress.tls }}
  tls:
    {{- range .Values.enterpriseFederationFrontend.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      {{- with .secretName }}
      secretName: {{ . }}
      {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.enterpriseFederationFrontend.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if $ingressSupportsPathType }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if $ingressApiIsStable }}
              service:
                name: {{ include "tempo.resourceName" $dict }}
                port:
                  number: {{ $.Values.enterpriseFederationFrontend.service.port }}
              {{- else }}
              serviceName: {{ include "tempo.resourceName" $dict }}
              servicePort: {{ $.Values.enterpriseFederationFrontend.service.port }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
