{{- if and .Values.enterprise.enabled .Values.enterpriseFederationFrontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tempo.resourceName" (dict "ctx" . "component" "federation-frontend-discovery") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tempo.labels" (dict "ctx" . "component" "enterprise-federation-frontend") | nindent 4 }}
  {{- with .Values.enterpriseFederationFrontend.serviceDiscovery.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 3100
      targetPort: 3100
    - name: grpc
      port: 9095
      protocol: TCP
      targetPort: 9095
      {{- if .Values.enterpriseFederationFrontend.appProtocol.grpc }}
      appProtocol: {{ .Values.enterpriseFederationFrontend.appProtocol.grpc }}
      {{- end }}
    - name: grpclb
      port: 9096
      protocol: TCP
      targetPort: grpc
      {{- if .Values.enterpriseFederationFrontend.appProtocol.grpc }}
      appProtocol: {{ .Values.enterpriseFederationFrontend.appProtocol.grpc }}
      {{- end }}
  publishNotReadyAddresses: true
  selector:
    {{- include "tempo.selectorLabels" (dict "ctx" . "component" "enterprise-federation-frontend") | nindent 4 }}
{{- end }}