{{- if gt (int .Values.querier.replicas) 1 }}
apiVersion: {{ include "tempo.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "tempo.querierFullname" . }}
  labels:
    {{- include "tempo.querierLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "tempo.selectorLabels" (dict "ctx" . "component" "querier" "memberlist" true) | nindent 6 }}
  maxUnavailable: 1
{{- end }}
