apiVersion: v2
name: grafana-agent-operator
description: A Helm chart for Grafana Agent Operator
type: application
version: 0.4.3
appVersion: "0.43.2"
home: https://grafana.com/docs/agent/v0.43/
icon: https://raw.githubusercontent.com/grafana/agent/v0.43.2/docs/sources/assets/logo_and_name.png
sources:
  - https://github.com/grafana/agent/tree/v0.43.2/static/operator
maintainers:
  - name: Grafana Agent Team
    email: grafana-agent-team@googlegroups.com
