# -- Overrides the chart's name
nameOverride: ""

# -- Overrides the chart's computed fullname
fullnameOverride: ""

annotations: {}

podAnnotations: {}

podSecurityContext: {}

imagePullSecrets: []

rbac:
  create: true

serviceAccount:
  create: true
  name:

image:
  registry: docker.io
  repository: grafana/agent-operator
  tag: v0.16.1
  pullPolicy: IfNotPresent

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
