# -- Overrides the chart's name
nameOverride: ""

# -- Overrides the chart's computed fullname
fullnameOverride: ""

annotations: {}

podAnnotations: {}

podSecurityContext: {}

rbac:
  create: true

serviceAccount:
  create: true
  name:

imagePullSecrets: []

image:
  registry: docker.io
  repository: grafana/agent-operator
  tag: v0.18.2
  pullPolicy: IfNotPresent

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
