{{- if .Values.rbac.pspEnabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "loki.fullname" . }}
  labels:
    {{- include "loki.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "loki.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "loki.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}

{{- if .Values.rbac.sccEnabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default:loki
  labels:
    {{- include "loki.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scc:hostmount-anyuid
subjects:
- kind: ServiceAccount
  name: loki
  name: {{ include "loki.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
