{{- if .Values.monitoring.rules.enabled }}
{{- with .Values.monitoring.rules }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    {{- include "loki.labels" $ | nindent 4 }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "loki.fullname" $ }}-rules
  namespace: {{ .namespace | default $.Release.Namespace }}
spec:
  {{- $.Files.Get "src/rules.yaml" | fromYaml | toYaml | nindent 2 }}
{{- end }}
{{- end }}
