{{- if gt (int .Values.queryFrontend.replicas) 1 }}
apiVersion: {{ include "tempo.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "tempo.queryFrontendFullname" . }}
  labels:
    {{- include "tempo.labels" (dict "ctx" . "component" "query-frontend") | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "tempo.selectorLabels" (dict "ctx" . "component" "query-frontend") | nindent 6 }}
  maxUnavailable: 1
{{- end }}
