{{- if and (gt (int .Values.ingester.replicas) 1) .Values.ingester.maxUnavailable }}
apiVersion: {{ include "loki.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "loki.ingesterFullname" . }}
  labels:
    {{- include "loki.ingesterLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "loki.ingesterSelectorLabels" . | nindent 6 }}
  {{- with .Values.ingester.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
{{- end }}
