{{- if .Values.podDisruptionBudget -}}
apiVersion: {{ include "tempo.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "tempo.ingesterFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tempo.labels" (dict "ctx" . "component" "ingester") | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "tempo.ingesterFullname" . }}
{{ toYaml .Values.podDisruptionBudget | indent 2 }}
{{- end }}
