{{- if gt (int .Values.ingester.replicas) 1 }}
apiVersion: {{ include "tempo.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "tempo.ingesterFullname" . }}
  labels:
    {{- include "tempo.labels" (dict "ctx" . "component" "ingester") | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "tempo.selectorLabels" (dict "ctx" . "component" "ingester") | nindent 6 }}
  maxUnavailable: {{ sub (.Values.ingester.replicas) (add (div .Values.ingester.config.replication_factor 2) 1) }}
{{- end }}
