{{- if .Values.grafanaAgent.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "ga-operator.grafanaAgent.serviceAccountName" . }}
  labels:
    app.kubernetes.io/component: grafanaAgent
{{ include "ga-operator.labels" . | indent 4 }}
{{- end -}}