{{- if .Values.grafanaAgent.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ga-operator.fullname" . }}-agent
  labels:
    app.kubernetes.io/component: grafanaAgent
{{ include "ga-operator.labels" . | indent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - /metrics
  verbs:
  - get
{{- end -}}