{{- if .Values.grafanaAgent.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ga-operator.fullname" . }}-agent
  labels:
    app.kubernetes.io/component: grafanaAgent
{{ include "ga-operator.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ga-operator.fullname" . }}-agent
subjects:
- kind: ServiceAccount
  name: {{ include "ga-operator.grafanaAgent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}