{{- if and .Values.grafanaAgent.metrics.enabled (not .Values.grafanaAgent.metrics.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ga-operator.fullname" . }}-metrics
  labels:
    app.kubernetes.io/component: metricsInstance
{{ include "ga-operator.labels" . | indent 4 }}
data:
  username: {{ .Values.grafanaAgent.metrics.username | b64enc | quote }}
  password: {{ .Values.grafanaAgent.metrics.password | b64enc | quote }}
{{- end }}