{{- if .Values.grafanaAgent.metrics.enabled -}}
apiVersion: monitoring.grafana.com/v1alpha1
kind: PrometheusInstance
metadata:
  name: {{ include "ga-operator.fullname" . }}-metrics
  labels:
    app.kubernetes.io/component: metricsInstance
{{ include "ga-operator.labels" . | indent 4 }}
spec:
  remoteWrite:
  - url: {{ .Values.grafanaAgent.metrics.remoteWriteURL}}
    basicAuth:
      username:
        name: {{ template "ga-operator.grafanaAgent.metricsInstance.apiKeySecretName" . }}
        key: username
      password:
        name: {{ template "ga-operator.grafanaAgent.metricsInstance.apiKeySecretName" . }}
        key: password

{{- if .Values.grafanaAgent.metrics.serviceMonitorNamespaceSelector }}
  serviceMonitorNamespaceSelector:
{{ toYaml .Values.grafanaAgent.metrics.serviceMonitorNamespaceSelector | indent 4 }}
{{ else }}
  serviceMonitorNamespaceSelector: {}
{{- end }}
{{- if .Values.grafanaAgent.metrics.serviceMonitorSelector }}
  serviceMonitorSelector:
{{ toYaml .Values.grafanaAgent.metrics.serviceMonitorSelector | indent 4 }}
{{ else }}
  serviceMonitorSelector: {}
{{- end }}

{{- if .Values.grafanaAgent.metrics.podMonitorNamespaceSelector }}
  podMonitorNamespaceSelector:
{{ toYaml .Values.grafanaAgent.metrics.podMonitorNamespaceSelector | indent 4 }}
{{ else }}
  podMonitorNamespaceSelector: {}
{{- end }}
{{- if .Values.grafanaAgent.metrics.podMonitorSelector }}
  podMonitorSelector:
{{ toYaml .Values.grafanaAgent.metrics.podMonitorSelector | indent 4 }}
{{ else }}
  podMonitorSelector: {}
{{- end }}

{{- if .Values.grafanaAgent.metrics.probeNamespaceSelector }}
  probeNamespaceSelector:
{{ toYaml .Values.grafanaAgent.metrics.probeNamespaceSelector | indent 4 }}
{{ else }}
  probeNamespaceSelector: {}
{{- end }}
{{- if .Values.grafanaAgent.metrics.probeSelector }}
  probeSelector:
{{ toYaml .Values.grafanaAgent.metrics.probeSelector | indent 4 }}
{{ else }}
  probeSelector: {}
{{- end }}

{{- end -}}