{{- if and (gt (int .Values.distributor.replicas) 1) .Values.distributor.maxUnavailable }}
apiVersion: {{ include "loki.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "loki.distributorFullname" . }}
  labels:
    {{- include "loki.distributorLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "loki.distributorSelectorLabels" . | nindent 6 }}
  {{- with .Values.distributor.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
{{- end }}
