{{- if .Values.federationFrontend.autoscaling.enabled }}
{{- $apiVersion := include "tempo.hpa.apiVersion" . -}}
apiVersion: {{ $apiVersion }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "tempo.resourceName" (dict "ctx" . "component" "federation-frontend") }}
  labels:
    {{- include "tempo.labels" (dict "ctx" . "component" "federation-frontend") | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "tempo.resourceName" (dict "ctx" . "component" "federation-frontend") }}
  minReplicas: {{ .Values.federationFrontend.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.federationFrontend.autoscaling.maxReplicas }}
  metrics:
  {{- with .Values.federationFrontend.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        {{- if (eq $apiVersion "autoscaling/v2") }}
        target:
          type: Utilization
          averageUtilization: {{ . }}
        {{- else }}
        targetAverageUtilization: {{ . }}
        {{- end }}
  {{- end }}
  {{- with .Values.federationFrontend.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        {{- if (eq $apiVersion "autoscaling/v2") }}
        target:
          type: Utilization
          averageUtilization: {{ . }}
        {{- else }}
        targetAverageUtilization: {{ . }}
        {{- end }}
  {{- end }}
{{- end }}
